### ISSUE TITLE
Comments on start of file causes unnecessary tab

### ISSUE THREAD

**Issue by tomyam1** [ikorennoy/logstash-intellij-plugin#16]
If there is a comment in the start of the file (could be empty, or with any content), it causes an indent after it when reformatting code.

When the comment is removed the indent is removed.

This only happens when the comment is the first thing in the file.

Before reformatting:

![image](https://user-images.githubusercontent.com/3265649/97803035-352c7700-1c50-11eb-8e45-9268dbec5cf6.png)

After reformatting:

![image](https://user-images.githubusercontent.com/3265649/97803044-45445680-1c50-11eb-823e-48f3409af978.png)

Reformatting after removing comment:

![image](https://user-images.githubusercontent.com/3265649/97803129-bab02700-1c50-11eb-994b-80564d74c02e.png)

webstorm 2020.2.3
IntelliJ Logstash plugin 0.62-2020.2

Many thanks for this plugin. It's really helpful!

**Comment by redfoos** [comment]
@tomyam1, hello! Thank you for your issue I will fix it as soon as possible.

**Comment by yquirion** [comment]
Hello,
I'm unable to install the plugin into version 2021.3 (Cummunity Edition) :

IntelliJ IDEA 2021.3 (Community Edition)
Build #IC-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 16
Non-Bundled Plugins:
    com.taff.plugin.orchide (2021.1.0.0-2019.3)

Kotlin: 213-1.5.10-release-949-IJ5744.223

Does the plugin will be avaiable for that version soon?

Thank you and best regards,
Yanick

**Comment by ikorennoy** [comment]
fixed
