### ISSUE TITLE
Incompatibility with JetBrains 2021.2 tools

### ISSUE THREAD

**Issue by airikh** [ikorennoy/logstash-intellij-plugin#19]
```
Plugin 'Logstash Config Files Support' (version '0.63-EAP') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92
```

I get a similar error in PyCharm.

Thank you for this great plugin. I hope you have time to support the new JetBrains tools.

**Comment by ikorennoy** [comment]
@airikh, hi, thanks for pointing this out
I did an update as soon as JB approved it the plugin will be available

**Comment by airikh** [comment]
Thanks a bunch, @ikorennoy! Much appreciated.
