### ISSUE TITLE
Unable to install into version  2021.3

### ISSUE THREAD

**Issue by yquirion** [ikorennoy/logstash-intellij-plugin#20]
Hello,
I'm unable to install the plugin into version 2021.3 (Cummunity Edition) :

IntelliJ IDEA 2021.3 (Community Edition)
Build #IC-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 16
Non-Bundled Plugins:
com.taff.plugin.orchide (2021.1.0.0-2019.3)

Kotlin: 213-1.5.10-release-949-IJ5744.223

Does the plugin will be avaiable for that version soon?

Thank you and best regards,
Yanick

**Comment by ikorennoy** [comment]
fixed
