### ISSUE TITLE
Doesn't work in newest version of IntelliJ

### ISSUE THREAD

**Issue by maltewhiite** [ikorennoy/logstash-intellij-plugin#21]
![image](https://user-images.githubusercontent.com/90693329/146160836-6e213e75-8583-476b-ac37-70d719c30a82.png)

**Comment by maltewhiite** [comment]
This is my version: 
![image](https://user-images.githubusercontent.com/90693329/146161784-43ec2db2-fca2-4954-b9d9-39b7fa82b36b.png)

**Comment by ikorennoy** [comment]
fixed
