### ISSUE TITLE
Incompatible with latest Intellij IDE builds

### ISSUE THREAD

**Issue by danieldunderfelt** [ikorennoy/logstash-intellij-plugin#34]
Hi! I'm trying to install this in Webstorm Build #WS-222.3345.108, but the plugin is incompatible. Any chance for a new version?

**Comment by ikorennoy** [comment]
@danieldunderfelt, hi!
Thank you for the issue I'll update the plugin as soon as possible.

**Comment by ikorennoy** [comment]
@danieldunderfelt, I've updated the plugin it is on JetBrains approval. Usually, it takes a day or two but if you need it urgently you can download the distribution from the releases page https://github.com/ikorennoy/logstash-intellij-plugin/releases/tag/v0.8.0 and install it manually.
