### ISSUE TITLE
Incompatible with latest Intellij IDE builds

### ISSUE THREAD

**Issue by ollie1** [ikorennoy/logstash-intellij-plugin#39]
Firstly, thank you for creating and maintaining this useful plugin!

Having updated my IDE to IntelliJ IDEA 2023.1, IntelliJ now refuses to load this plugin with the message:
"Incompatible: requires IDE build 223.* or earlier"

Would it be posssible to update the plugin to support the latest IntelliJ IDE?

**Comment by ikorennoy** [comment]
@ollie1, thank you for the information, I'll update it ASAP.

I would appreciate it if you could rate the plugin in the JB marketplace [Logstash Config Files Support
](https://plugins.jetbrains.com/plugin/12373-logstash-config-files-support)

**Comment by ikorennoy** [comment]
Updated. Now the plugin has to be approved by JetBrains, usually not more than a couple of days.
