### ISSUE TITLE
Incompatible with latest Intellij IDE builds

### ISSUE THREAD

**Issue by nWmCZ** [ikorennoy/logstash-intellij-plugin#40]
Hi,
first of all, thank you for the plugin, it's awesome.
Secondly I am using IntelliJ IDEA 2023.2 and it says:

> Plugin 'Logstash Config Files Support' (version '0.8.1') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IC-232.8660.185

Could you please add support for newer versions?

Thanks

**Comment by maosmurf** [comment]
See https://github.com/ikorennoy/logstash-intellij-plugin/pull/41

**Comment by adamzanyline** [comment]
Hi @nWmCZ  - I fixed the issue via https://github.com/ikorennoy/logstash-intellij-plugin/pull/41
Feel free to pull and build locally and "install from disk"

**Comment by nWmCZ** [comment]
Thank you, it works.

**Comment by ikorennoy** [comment]
The new version is available in the JetBrains Marketplace.
